### ISSUE TITLE
pass currentPath to UserRepo function 

### ISSUE THREAD

**Issue by arshadkazmi42** [gh-conf/upstream-core#6]
Let's pass currentPath to userRepo function  here
https://github.com/gh-conf/upstream-core/blob/master/index.js#L22

We need to fix this, once https://github.com/gh-conf/gh-conf-parse/issues/16 this issue has been closed

**Comment by arunr3ddy** [comment]
I'll Work on this issue

**Comment by skathuria29** [comment]
Hi! Is this issue still up for grabs?

**Comment by arshadkazmi42** [comment]
@skathuria29 No, we have already received a PR for this at #7
